package ga.local_connect.api.enumeration;

public enum APIErrorType {
    INVALID_NUMBER,

    INVALID_URI,
    INVALID_METHOD,
    INVALID_PARAMETER,

    INVALID_SESSION_SECRET,
    INVALID_USER_SECRET,

    ENDPOINT_NOT_FOUND,

    USER_NOT_FOUND,
    PROFILE_NOT_FOUND,

    UNKNOWN_ERROR
}
