package ga.local_connect.api.enumeration;

public enum APIErrorType {
    INVALID_NUMBER,

    INVALID_URI,
    INVALID_METHOD,
    INVALID_PARAMETER,

    INVALID_SESSION_SECRET,
    INVALID_USER_SECRET,

    INVALID_OBJECT_TYPE,
    INVALID_IMAGE_FORMAT,

    ENDPOINT_NOT_FOUND,

    PERMISSION_NOT_FOUND,
    TYPE_NOT_FOUND,
    REGION_NOT_FOUND,
    GROUP_NOT_FOUND,
    USER_NOT_FOUND,
    BOARD_NOT_FOUND,
    EVENT_NOT_FOUND,
    POST_NOT_FOUND,
    PROFILE_NOT_FOUND,
    IMAGE_NOT_FOUND,
    ATTACHMENT_NOT_FOUND,
    SERVICE_NOT_FOUND,

    IO_ERROR,
    UNKNOWN_ERROR
}
